# Generated by Django 2.2.3 on 2019-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_in', models.IntegerField()),
                ('total_out', models.IntegerField()),
            ],
            options={
                'db_table': 'cash',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'fee',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.IntegerField()),
                ('february', models.IntegerField()),
                ('march', models.IntegerField()),
                ('april', models.IntegerField()),
                ('may', models.IntegerField()),
                ('june', models.IntegerField()),
                ('july', models.IntegerField()),
                ('august', models.IntegerField()),
                ('september', models.IntegerField()),
                ('october', models.IntegerField()),
                ('november', models.IntegerField()),
                ('december', models.IntegerField()),
            ],
            options={
                'db_table': 'month',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=15)),
                ('class_no', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('student_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.IntegerField()),
                ('total_paid_this_year', models.IntegerField()),
                ('total_balance_this_year', models.IntegerField()),
            ],
            options={
                'db_table': 'year',
            },
        ),
    ]
