# Generated by Django 2.2.3 on 2019-09-13 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_cashrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrecords',
            name='date_filed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
