# Generated by Django 2.2.3 on 2019-09-14 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20190913_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.IntegerField()),
                ('student_roll_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=30)),
                ('fee_month', models.CharField(max_length=30)),
                ('paid_amount', models.IntegerField()),
                ('date_filed', models.DateTimeField(default=datetime.datetime(2019, 9, 14, 15, 5, 46, 54878))),
            ],
            options={
                'db_table': 'fee_records',
            },
        ),
        migrations.AlterField(
            model_name='cashrecords',
            name='date_filed',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 15, 5, 46, 53877)),
        ),
    ]
