# Generated by Django 2.2.3 on 2019-09-14 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20190914_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField()),
            ],
            options={
                'db_table': 'fee_challan',
            },
        ),
        migrations.AlterField(
            model_name='cashrecords',
            name='date_filed',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 18, 10, 46, 733701)),
        ),
        migrations.AlterField(
            model_name='feerecords',
            name='challan_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feerecords',
            name='date_filed',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 18, 10, 46, 735702)),
        ),
    ]
