# Generated by Django 2.2.3 on 2019-09-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20190914_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('fee_description', models.CharField(max_length=300)),
                ('date_filed', models.DateTimeField()),
            ],
            options={
                'db_table': 'random_challan',
            },
        ),
        migrations.AlterField(
            model_name='cashrecords',
            name='date_filed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feerecords',
            name='date_filed',
            field=models.DateTimeField(),
        ),
    ]
