# Generated by Django 2.2.3 on 2019-09-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_auto_20190916_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomchallan',
            name='date_filed',
            field=models.DateTimeField(),
        ),
    ]
